VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Risoluto/risoluto-dev"
  config.vm.boot_timeout = 60
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

  config.ssh.username = "root"
#  config.ssh.password = "root"

  config.vm.synced_folder ".", "/vagrant",    disabled: true

#  config.vm.network :forwarded_port, guest:80, host:8080, id:"http"
#  config.vm.network :forwarded_port, guest:443, host:8443, id:"https"
#  config.vm.network :forwarded_port, guest:9000, host:9000, id:"xdebug"

  config.vm.network :private_network, ip: "192.168.56.10"

  config.vm.provision "shell", path: "setup.sh", run: "always"
end
